version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - app_network

  mysql:
    image: "mysql:latest"
    container_name: mysql_service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: order_management
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 10s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: golang_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy 
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - app_network
    restart: always 

networks:
  app_network:
    driver: bridge
